### ISSUE TITLE
Flickering and unresponsive desktop after opening the lid

### ISSUE THREAD

**Issue by eriksjolund** [eriksjolund/install-linux-hp-elitebook-850-g5#4]
This issue is regarding **Ubuntu 18.10** with **Xorg**. I haven't tried if using **Wayland** would change things.

About every 20th time after opening the lid this happen:

1. The left desktop panel seems to be active but when I hover with the mouse pointer over the application icons,  text tips like "Firefox Web Browser" and "Ubuntu software" are popping up just to the right of that desktop panel but they don't go away. The rest of the screen is flickering, alternating between being black and displaying the desktop. 
2. Go to the top right corner and click with the left mouse button.
3. Click the **pause** icon. Now the computer screen goes black and the power button on the keyboard starts the blink.
3. Press the power button. After a few seconds a text field for entering my password is shown (the normal unlock screen). One thing is very strange:
The left desktop panel is shown at the same time as the normal unlock screen (for entering a password).
4. When I enter my password, my normal desktop is shown and everything works again.

**Comment by eriksjolund** [comment]
Problem solved. It seems some of the latest updates to Ubuntu 18.10 have fixed the issue.
Since a few weeks this problem does not show up anymore in my laptop.

**Comment by eriksjolund** [comment]
Unfortunately, it happened again. 
(I am now running XWayland by the way)

    user@laptop:~$ pgrep -fl wayland
    1870 gdm-wayland-ses
    1995 Xwayland
    user@laptop:~$

**Comment by dkocich** [comment]
I had this problem for few months with my Dell and I believe that this is actually related to graphics card drivers and not the notebook itself, info e.g. https://askubuntu.com/questions/1033425/18-04-nvidia-graphics-screen-flickering

**Comment by eriksjolund** [comment]
I think this issue has been fixed by now.
