### ISSUE TITLE
Hangs at reboot

### ISSUE THREAD

**Issue by Madko** [eriksjolund/install-linux-hp-elitebook-850-g5#7]
Hi,

Do you have issues when rebooting, computer hangs on a black screen like forever ?

I can see the complete linux shutdown, than a black screen, at that's all... Only the keyboard backlight is responsive. I've try to wait like 20 minutes, nothing. Computer stays on, sometime IO activity LED is blinking (1 blink every 5s).
So I have to press power button for 10s...
Looks like Linux doesn't send the right signal to reboot. Powering off works fine tho.

I'm on Fedora 29 (kernel 4.20) but I'd like to know if you have this bug with Ubuntu.

I've disabled fast boot in the BIOS (v1.04.00 9/12/2018) and in Windows. Rebooting from Windows is working fine.

Thanks

**Comment by eriksjolund** [comment]
I don't have any problems rebooting.  (Running Ubuntu 18.10)
This my hardware spec:

    HP IDS UMA i5-8250U 850 G5 Base NB PC 
    FreeDOS 2.0 SE/FI 
    No Webcam 
    15.6 inch FHD (1920x1080) Anti-Glare LED UWVA 220 slim 
    32GB (2x16GB) DDR4 2400 
    1TB PCIe NVMe Three Layer Cell Solid State Drive 
    No Near Field Communication (No NFC) 
    Intel 8265 ac 2x2 nvP +Bluetooth 4.2 WW with 2 Antennas 
    No WWAN 
    No Fingerprint Sensor 
    Active SmartCard 
    3 Cell 56 WHr Long Life 
    45 Watt Smart nPFC Right Angle AC Adapter 
    C5 1.8m Sticker Conventional Power Cord SE/FI 
    3/3/0 Warranty EURO 
    No vPro AMT supported 
    DIB HP Basic Carrying Case 
    Country Localization SE/FI 
    Dual Point with numeric keypad spill-resistant Collaboration SE/FI 
    EU RED Pictogram Label 
    Core i5 G8 Label 
    HP 1 year Priority Management Service for PCs (1000+ seats) 
    HP 3 year Next Business Day Onsite Notebook Only Hardware Support 
    HP Operations Service


I am not running any Windows.

**Comment by ghost** [comment]
Not having this issue either on Ubuntu 18.10

**Comment by Madko** [comment]
I forgot to say that there is a easy fix, just add `reboot=efi` to kernel boot parameters.
